# Generated by Django 5.2.4 on 2025-07-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book entries'), ('can_change_book', 'Can change book entries'), ('can_delete_book', 'Can delete book entries')]},
        ),
    ]
