# Generated by Django 5.2.4 on 2025-07-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_customuser_date_of_birth_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
