# Generated by Django 5.2.5 on 2025-09-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
