# Generated by Django 5.2.4 on 2025-07-28 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_author_library_alter_loan_options_alter_book_isbn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='returned_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='member',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('book', 'user', 'return_date')},
        ),
    ]
